# Generated by Django 4.0.5 on 2022-07-23 07:58

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ModelApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='create_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 23, 7, 58, 9, 896378, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='person',
            name='update_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 23, 7, 58, 9, 896421, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='schools',
            name='prefecture',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='ModelApp.prefectures'),
        ),
        migrations.AlterField(
            model_name='students',
            name='prefecture',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='ModelApp.prefectures'),
        ),
        migrations.AlterField(
            model_name='students',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='ModelApp.schools'),
        ),
    ]
