# Generated by Django 4.0.5 on 2022-07-05 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField()),
                ('name', models.CharField(max_length=50)),
                ('grade', models.IntegerField()),
                ('pictures', models.FileField(upload_to='student/')),
            ],
            options={
                'db_table': 'students',
            },
        ),
    ]
