# Generated by Django 4.0.5 on 2022-07-05 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FormApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='students',
            old_name='pictures',
            new_name='picture',
        ),
    ]
